### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by gammaw** [mmmnmnm/lahmacun_arcsi#31]
From `aguni.log` (`web` container on arcsi server):

```
[2020-11-04 08:07:17 +0000] [454] [ERROR] Exception on /arcsi/item [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/app/arcsi/api/item.py", line 144, in add_item
    process_media(request.files, new_item)
  File "/app/arcsi/api/utils.py", line 128, in process_media
    if image_file_path:
UnboundLocalError: local variable 'image_file_path' referenced before assignment
```

**Comment by gammaw** [comment]
No witness, lack of context. Closing it.
